enableGlobalCache: true

npmPublishRegistry: "https://registry.npmjs.com"

npmRegistryServer: "https://registry.npmjs.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"

preferDeferredVersions: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.1.1.js
